app_id: BB2359F2-A4F9-4FC2-BCDD-61289CB9419A
publisher: Somoon
publisher_url: https://github.com/Somoon/Banano-Keeper
display_name: Banano Keeper
create_desktop_icon: true
install_dir_name: BananoKeeper
locales:
  - en